language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t soccertrash/feed-api project/udagram-api/feed-api
  - docker build -t soccertrash/user-api project/udagram-api/user-api
  - docker build -t soccertrash/frontend project/udagram-frontend/
  - docker build -t soccertrash/nginx project/nginx/

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push soccertrash/user-api
  - docker push soccertrash/feed-api
  - docker push soccertrash/frontend
  - docker push soccertrash/nginx
