apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-api
  name: user-api-svc
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: user-api
  type: ClusterIP
status:
  loadBalancer: {}
