apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: feed-api
  name: feed-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: feed-api
    spec:
      containers:
      - image: soccertrash/feed-api
        name: feed-api
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
